esphome:
  name: bluetooth-proxy
  friendly_name: Bluetooth Proxy

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENCRYPTION_KEY

ota:
  password: !secret OTA_PASSWORD

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  #ap:
  #  ssid: "Bluetooth-Proxy Fallback Hotspot"
  #  password: "REMOVED"

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  