esphome:
  name: bluetooth-proxy
  friendly_name: Bluetooth Proxy


esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENCRYPTION_KEY

ota:
  password: !secret OTA_PASSWORD

wifi:
  networks:
  - ssid: !secret WIFI_SSID
    password: !secret WIFI_PASSWORD
  domain: !secret NET_DOMAIN
  reboot_timeout: 15min


  # Enable fallback hotspot in case wifi connection fails
  #ap:
  #  ssid: "Bluetooth-Proxy Fallback Hotspot"
  #  password: "REMOVED"

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
  