substitutions:
  devicename: "esp32-poe-test"
  upper_devicename: "esp32-poe-test"

esphome:
  name: "${devicename}"
  #friendly_name: "${upper_devicename}"

esp32:
  board: wesp32
  framework:
    type: arduino

ethernet:
  type: RTL8201
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0
  domain: !secret NET_DOMAIN

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

#captive_portal:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/wt32-eth01.yaml@main

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
