---
substitutions:
  system_name: frontroomlamp-s31
  host_name: FrontroomLamp-s31.nickeson.net
  friendly_name: Frontroom Lamp S31
  device_description: Frontroom Lamp S31 Device
  #current_res: "0.00245"
  #voltage_div: "963"

packages:
  device: !include devices/sonoff_s31.yaml