# BBQ Temp Monitor
substitutions:
  devicename: "grill"
  upper_devicename: "Grill"

esphome:
  name: "${devicename}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  # name_add_mac_suffix: true
  
esp8266:
  board: nodemcuv2
  # https://esphome.io/devices/nodemcu_esp8266.html

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password


preferences:
  # the default of 1min is far too short--flash chip is rated
  # for approx 100k writes.
  flash_write_interval: "48h"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: 10.28.20.41
      gateway: 10.28.20.1
      subnet: 255.255.255.0
  domain: !secret NET_DOMAIN
  reboot_timeout: 15min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${upper_devicename} Hotspot
    password: !secret hotspot_pass

captive_portal:
  # https://esphome.io/components/captive_portal.html

spi:
  #max31855 & max31865 on the same spi 
  miso_pin: D6 #done
  mosi_pin: D7 #done
  clk_pin: D3 #done

sensor:
  - platform: max31855
  # max31855: https://esphome.io/components/sensor/max31855.html
    name: "Grill Probe Temperature"
    cs_pin: D2 #done
    #temperature:
    #  id: temp
    #  name: ${upper_devicename} Temperature
    #humidity:
    #  id: humidity
    #  name: ${upper_devicename} Humidity
    #address: 0x44
    update_interval: 15s #default is 60s
    
  
  - platform: max31865
  # max31865 https://esphome.io/components/sensor/max31865.html
    name: "Grill Ambient Temperature"
    cs_pin: D4 #done
    # Need to check if below is best/correct method
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 15s #default is 60s
  