---
substitutions:
  system_name: test-s31
  host_name: test-s31.nickeson.net
  friendly_name: Test S31
  device_description: Test S31 Device
  #current_res: "0.00245"
  #voltage_div: "963"

packages:
  device: !include devices/sonoff_s31_rebuild.yaml