# From: https://github.com/gabe565/esphome-configs/

packages:
  <<: !include_dir_named ../components/common
  wifi: !include ../components/hardware/wifi.yaml
  board: !include ../boards/esp_01.yaml
  opengarage: !include ../components/packages/opengarage.yaml

substitutions:


  # SR04 sensors can be noisy. The median is taken to prevent noisy data.
  # Higher values will slow down the distance sensor's responsiveness,
  # but will result in more consistent data.
  # See https://esphome.io/components/sensor/index.html#median
  distance_median_window_size: '31'
  # When the first value should be sent. Must be lower than the distance_median_window_size.
  distance_median_send_first_at: '5'

  # Sound the alarm on open/close
  # RTTL format references:
  #  - https://esphome.io/components/rtttl.html?highlight=rtttl#common-beeps
  #  - https://en.wikipedia.org/wiki/Ring_Tone_Transfer_Language
  open_alarm: 'false'
  open_alarm_rtttl: 'two_short:d=4,o=6,b=100:c,p,c'
  # open_alarm_rtttl: 'long:d=1,o=6,b=100:c'
  # open_alarm_rtttl: 'open_pulse:d=16,o=5,b=100:c,c6,p.,c,c6,p.,c,c6,p.'
  # open_alarm_rtttl: 'open_slide:d=128,o=5,b=100:c,d,e,g,4c6.,4p,c,d,e,g,4c6.,4p'

  close_alarm: 'false'
  close_alarm_rtttl: 'two_short:d=4,o=5,b=100:c,p,c'
  # close_alarm_rtttl: 'long:d=1,o=5,b=100:c'
  # close_alarm_rtttl: 'close_pulse:d=16,o=5,b=100:c6,c,p.,c6,c,p.,c6,c,p.'
  # close_alarm_rtttl: 'close_slide:d=128,o=5,b=100:c6,g,e,d,4c.,4p,c6,g,e,d,4c.,4p'
