wifi:
  ssid: !secret WIFI_SSD
  password: !secret WIFI_PASSWORD
  domain: !secret NET_DOMAIN
  fast_connect: True
  power_save_mode: none
  #manual_ip:
    #static_ip: ${ip_address}
    #gateway: ${gateway}
    #subnet: 255.255.255.0


  ap:
    ssid: "${devicename} Fallback"
    password: !secret FALLBACK_PASS

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ENCRYPTION_KEY

ota:
  password: !secret OTA_PASSWORD

# Enable Time Component
time:
  - platform: sntp
    servers: !secret NTP_SERVER_IP
    timezone: !secret TIMEZONE

# This section is optional. However, I configure all of my devices to also use MQTT, along with home assistant directly. 
# MQTT allows me to easily integrate them into other systems.
mqtt:
  broker: !secret MQTT_BROKER
  username: mqtt
  password: !secret MQTT_PASSWORD
  discovery: false
  log_topic:
    topic: esphome/logs/${devicename}
    level: ERROR
  topic_prefix: esphome
  birth_message:
    topic: esphome/state/${devicename}
    payload: online
  will_message:
    topic: esphome/state/${devicename}
    payload: offline
